### ISSUE TITLE
No spawn after restart

### ISSUE THREAD

**Issue by FenixDK** [katotekii/uniq_vending_standalone#1]
It seems that the script needs a reload after restart to start spawning the machines that were placed before the restart. The server is on qb and console does not produce any errors.

**Comment by katotekii** [comment]
> It seems that the script needs a reload after restart to start spawning the machines that were placed before the restart. The server is on qb and console does not produce any errors.

redownload and try again

**Comment by FenixDK** [comment]
Fixed. Thanks a lot! Also, thanks for your effort to the community!
